# Auto-generated by safe_rl.pipeline.stage5_failure_audit
# Review the listed failure seeds in SUMO GUI.

# cv_prediction_shield
& "E:\Programs\EnvAnaconda3\envs\pytorch\python.exe" -m safe_rl.tools.replay_episode --replay "E:\WcDT_RL\WcDT_RL.pytest_tmpcomparative_verify\test_stage5_failure_audit_iden0\runs\safe_rl_audit\stage5\replay\cv_prediction_shield_seed_7.json" --gui --delay-ms 200
