from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

from safe_rl.pipeline.common import make_env
from safe_rl.utils.config import load_config
from safe_rl.utils.progress import stage_log


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Replay a recorded SAFE_RL episode in SUMO.")
    parser.add_argument("--replay", required=True, help="Path to replay JSON generated by Stage1/4/5.")
    parser.add_argument("--config", default=None, help="Optional YAML config overlay.")
    parser.add_argument("--gui", action="store_true", help="Use sumo-gui instead of sumo.")
    parser.add_argument("--sumo-binary", default=None, help="Explicit SUMO binary, e.g. sumo-gui.")
    parser.add_argument("--delay-ms", type=float, default=0.0, help="Sleep after each SUMO simulation step for smooth GUI playback.")
    parser.add_argument("--control-delay-ms", type=float, default=0.0, help="Additional sleep between recorded RL control actions.")
    parser.add_argument("--risk-checkpoint", default=None, help="Override risk checkpoint for shield-enabled replays.")
    parser.add_argument(
        "--ego-color",
        default="255,0,0,255",
        help="RGBA color for the replay ego vehicle. Use an empty string to disable.",
    )
    return parser.parse_args()


def _parse_rgba(value: str) -> tuple[int, int, int, int] | None:
    if not value:
        return None
    parts = [part.strip() for part in value.split(",")]
    if len(parts) not in (3, 4):
        raise ValueError("--ego-color must be R,G,B or R,G,B,A")
    channels = [int(part) for part in parts]
    if len(channels) == 3:
        channels.append(255)
    if any(channel < 0 or channel > 255 for channel in channels):
        raise ValueError("--ego-color channels must be in [0, 255]")
    return tuple(channels)  # type: ignore[return-value]


def _color_ego(env, rgba: tuple[int, int, int, int] | None) -> None:
    if rgba is None:
        return
    traci = getattr(env, "_traci", None)
    if traci is None:
        return
    try:
        if env.ego_id in traci.vehicle.getIDList():
            traci.vehicle.setColor(env.ego_id, rgba)
    except Exception:
        return


def run() -> None:
    args = parse_args()
    replay_path = Path(args.replay)
    with replay_path.open("r", encoding="utf-8") as file:
        replay = json.load(file)
    cfg = load_config(args.config)
    if args.sumo_binary:
        cfg.scenario["sumo_binary"] = args.sumo_binary
    elif args.gui:
        cfg.scenario["sumo_binary"] = "sumo-gui"
    if replay.get("run_id"):
        cfg.run["run_id"] = replay["run_id"]

    actions = [int(action) for action in replay.get("actions", [])]
    seed = int(replay["seed"])
    shield_enabled = bool(replay.get("shield_enabled", False))
    risk_checkpoint = args.risk_checkpoint or replay.get("risk_checkpoint")
    ego_color = _parse_rgba(str(args.ego_color))
    stage_log("replay", f"file={replay_path}")
    stage_log("replay", f"stage={replay.get('stage')} episode={replay.get('episode')} seed={seed}")
    stage_log("replay", f"sumo_binary={cfg.scenario.sumo_binary} shield={shield_enabled}")
    stage_log("replay", f"actions={len(actions)}")

    env = make_env(
        cfg,
        seed=seed,
        shield_enabled=shield_enabled,
        risk_checkpoint=risk_checkpoint,
        sumo_step_delay_ms=max(0.0, float(args.delay_ms)),
    )
    try:
        obs, _info = env.reset(seed=seed)
        _color_ego(env, ego_color)
        terminated = truncated = False
        for step, action in enumerate(actions):
            if terminated or truncated:
                break
            obs, reward, terminated, truncated, info = env.step(action)
            _color_ego(env, ego_color)
            stage_log(
                "replay",
                f"step={step} action={action} reward={float(reward):.3f} "
                f"done={terminated or truncated} reason={info.get('done_reason', '')}",
            )
            if args.control_delay_ms > 0:
                time.sleep(args.control_delay_ms / 1000.0)
        stage_log("replay", f"episode_report={env.episode_report()}")
    finally:
        env.close()


if __name__ == "__main__":
    run()
